apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mesheryistio.serviceAccountName" . }}
  labels:
{{- include "mesheryistio.labels" . | nindent 4 }}
rules:
- apiGroups: ["networking.istio.io"]
  resources:
  - virtualservices
  - destinationrules
  - serviceentries
  - gateways
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete