apiVersion: v1
kind: Service
metadata:
  name: {{ include "mesheryistio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mesheryistio.labels" . | nindent 4 }}
  annotations:
{{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mesheryistio.selectorLabels" . | nindent 4 }}
