{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mesheryistio.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "mesheryistio.labels" . | nindent 4 }}
{{- end -}}
