name: Release Drafter

on:
  push:
    # Releases to be made from master branch
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
